### ISSUE TITLE
infer schema

### ISSUE THREAD

**Issue by tsusanto** [databricks/spark-xml#239] opened 2017-02-15 22:09 UTC
I know I can provide a schema but it's fairly complex and it will be a lot of typing,  the inferred schema is actually mostly fine except for 1. It should have been inferred as a string but instead it inferred it as an int data type so all the leading zeros were dropped. All values actually have leading zeros.

Is it possible to make it infer it as a string?

**Comment by HyukjinKwon** [comment] 2017-02-16 00:18
Ah, I guess it is a duplicate of #205 per requests of this feature, I am willing to add this. Let me open a PR soon and then discuss there further. Thanks for opening this issue.

**Comment by tsusanto** [comment] 2017-02-16 00:51
ok thanks!

**Closed** 2018-12-21 14:00 UTC
Labels: duplicate
