### ISSUE TITLE
Cannot cache empty XML Dataframe

### ISSUE THREAD

**Issue by maarest** [databricks/spark-xml#112] opened 2016-04-21 03:40 UTC
Hi,

Take an XML doc and read it. 

```
val rowTag = "INTENDEDTOBEWRONG"
val df = sqlContext.read
        .format("xml")
        .option("rowTag", rowTag)
        .option("treatEmptyValuesAsNulls", "true")
        .option("samplingRatio", "1")
        .load(path)
```

This returns a dataframe that's empty, as you can see, and you can run the following code:

```
df.count() == 0
```

But the following code doesn't work

``` 
df.cache()
df.count() == 0
```

> 
> java.lang.UnsupportedOperationException: empty.minBy
> 	at scala.collection.TraversableOnce$class.minBy(TraversableOnce.scala:252)
> 	at scala.collection.AbstractTraversable.minBy(Traversable.scala:104)
> 	at org.apache.spark.sql.columnar.InMemoryColumnarTableScan$$anonfun$9.apply(InMemoryColumnarTableScan.scala:282)
> 	at org.apache.spark.sql.columnar.InMemoryColumnarTableScan$$anonfun$9.apply(InMemoryColumnarTableScan.scala:271)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:88)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 16/04/21 13:35:15 ERROR TaskSetManager: Task 0 in stage 10.0 failed 1 times; aborting job
> Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 10.0 failed 1 times, most recent failure: Lost task 0.0 in stage 10.0 (TID 19, localhost): java.lang.UnsupportedOperationException: empty.minBy
> 	at scala.collection.TraversableOnce$class.minBy(TraversableOnce.scala:252)
> 	at scala.collection.AbstractTraversable.minBy(Traversable.scala:104)
> 	at org.apache.spark.sql.columnar.InMemoryColumnarTableScan$$anonfun$9.apply(InMemoryColumnarTableScan.scala:282)
> 	at org.apache.spark.sql.columnar.InMemoryColumnarTableScan$$anonfun$9.apply(InMemoryColumnarTableScan.scala:271)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:88)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> Driver stacktrace:
> 	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
> 	at scala.Option.foreach(Option.scala:257)
> 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1496)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1458)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1447)
> 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
> 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:567)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1822)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1835)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1848)
> 	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:215)
> 	at org.apache.spark.sql.execution.Limit.executeCollect(basicOperators.scala:207)
> 	at org.apache.spark.sql.DataFrame$$anonfun$collect$1.apply(DataFrame.scala:1385)
> 	at org.apache.spark.sql.DataFrame$$anonfun$collect$1.apply(DataFrame.scala:1385)
> 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
> 	at org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:1903)
> 	at org.apache.spark.sql.DataFrame.collect(DataFrame.scala:1384)
> 	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1314)
> 	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1377)

Can you reproduce?

**Comment by HyukjinKwon** [comment] 2016-04-21 07:02
@maarest Hm.. Could you please share your data?

**Comment by maarest** [comment] 2016-04-22 00:15
Full code:

```

    var goodRowTag1 = "RowTag1"
    var goodRowTag2 = "RowTag2"
    var badRowTag = "RowTag3"

    val temp = File.createTempFile("xml",".tmp")
    val bw = new BufferedWriter(new FileWriter(temp))
    // create dummy data that can be good or bad
    val xml_string = "<Root>" +
      s"<$goodRowTag1><col1>foo</col1><col2>foo</col2></$goodRowTag1>" +
      s"<$goodRowTag1><col1>foo2</col1><col2>foo2</col2></$goodRowTag1>" +
      s"<$goodRowTag2><$badRowTag>foo3</$badRowTag><col2>foo3</col2></$goodRowTag2>" +
      s"<$goodRowTag2><$badRowTag>foo4</$badRowTag><col2>foo4</col2></$goodRowTag2>" +
      s"<$badRowTag><col5>foo5</col5><col6>foo6</col6></$badRowTag>" +
      s"<$badRowTag><col5>foo6</col5><col6>foo6</col6></$badRowTag>" +
      "</Root>"
    bw.write(xml_string)
    bw.close()
    temp.deleteOnExit()

    val rowTag = "INTENDEDTOBEWRONG"
    val df = sqlContext.read
      .format("xml")
      .option("rowTag", rowTag)
      .option("treatEmptyValuesAsNulls", "true")
      .option("samplingRatio", "1")
      .load(temp.getAbsolutePath)

    println(df.count() == 0)
    df.cache()
    println(df.count() == 0)
```

You'll see how things crash

**Comment by HyukjinKwon** [comment] 2016-04-25 09:26
@maarest Is this because of `rowTag`, `INTENDEDTOBEWRONG`? Could you try with `Root` or `RowTag1` instead?

**Comment by maarest** [comment] 2016-04-25 22:52
Hi @HyukjinKwon . It's definitely because of the rowTag being wrong. I would expect an empty Dataframe to be returned, which is what's returned. Oddly enough though, df.count() works before being cached.

Please also note that the standard [emptyDataFrame ](https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/sql/SQLContext.html#emptyDataFrame()) can get cached without issues. 

Therefore something must be going on with your library.

I highlighted this case because my spark program is being driven by config files, which can be wrong. If the user supplies to wrong rowtag, my program crashes because I cache the dataframe nonetheless.

**Comment by HyukjinKwon** [comment] 2016-04-25 23:46
Ah, I see thanks! Let me check Spark internal data sources and will update this library to be consistent with them if it is not.

**Comment by HyukjinKwon** [comment] 2016-04-27 03:55
@maarest I think it is an issue in Spark. Could you tell me your Spark version? I just tested this I it looks fine with Spark 1.6.0. Let me search the related JIRA if your version is lower.

Thanks for your codes it was easy to test.

**Comment by HyukjinKwon** [comment] 2016-04-27 04:05
@maarest I think https://issues.apache.org/jira/browse/SPARK-9627 might be related with this if you are using Spark less than 1.4.x.

**Comment by maarest** [comment] 2016-04-27 04:17
I'm using 1.5.1 so that's weird... can you try with 1.5.1 and confirm the issue or not?

**Comment by HyukjinKwon** [comment] 2016-04-27 04:23
Oh, I could reproduce. Let me try to search the JIRA.

**Comment by HyukjinKwon** [comment] 2016-09-09 10:37
I am closing this as it seems not the issue in this library. Please feel free to reopen this! Thank you for reporting this!

**Closed by HyukjinKwon** 2016-09-09 10:37 UTC
Labels: not a spark-xml issue
