### ISSUE TITLE
com.databricks.spark.xml.parsers.StaxXmlGenerator

### ISSUE THREAD

**Issue by anayyar82** [databricks/spark-xml#151] opened 2016-08-12 14:47 UTC
while reading the large xml getting below issue. any idea ?

java.lang.NullPointerException
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:131)
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$$anonfun$apply$4.apply(StaxXmlGenerator.scala:129)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.databricks.spark.xml.parsers.StaxXmlGenerator$.apply(StaxXmlGenerator.scala:129)
	at com.databricks.spark.xml.package$XmlSchemaRDD$$anonfun$2$$anon$1.next(package.scala:113)
	at com.databricks.spark.xml.package$XmlSchemaRDD$$anonfun$2$$anon$1.next(package.scala:101)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply$mcV$sp(PairRDDFunctions.scala:1109)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply(PairRDDFunctions.scala:1108)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply(PairRDDFunctions.scala:1108)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1206)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1116)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1095)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by HyukjinKwon** [comment] 2016-08-13 01:37
Do you mind if I ask the data if it is okay? I would like to test and narrow down the case.

**Comment by anayyar82** [comment] 2016-08-15 14:34
Sure data is Okay,  attaching the XML. Can you please provide the sample how to parse it

<FWD A20="QPP" A40="DE" B00="AB" TIM="1466658039753" END="1466658041568" TID="314786023654607885">
    <ns8:OTA_AirLowFareSearchRQ
        xmlns:ns5="http://www.w3.org/1999/xlink"
        DirectFlightsOnly="false" MaxResponses="0" ResponseVersion="1.9.4" Target="a" Version="1.9.4">
        <ns8:POS>
            <ns8:Source AccountingCode="I3B" OfficeCode="23" PersonalCityCode="Q3PP" PseudoCityCode="QP33P">
                <ns8:RequestorID ID="13" Type="11">
                    <ns8:CompanyName Code="3f">3f</ns8:CompanyName>
                </ns8:RequestorID>
            </ns8:Source>
        </ns8:POS>

  </ns8:OTA_AirLowFareSearchRQ>
</FWD>

**Comment by HyukjinKwon** [comment] 2016-08-23 01:16
Do you mind close this if this is a duplicate of #153 please?

**Closed** 2016-08-23 01:52 UTC
Labels: duplicate
