### ISSUE TITLE
attributes are ignored when specifying a schema

### ISSUE THREAD

**Issue by Jeongmin-Lee** [databricks/spark-xml#375] opened 2019-01-09 07:32 UTC
I want to get a nested xml as String. But, Attributes are ignored.
this is sample xml.

```xml
<record>
  <title>hihihihi &amp; tttt  </title>
  <info type="text" word="apps">
    <test1>test_</test1>
    <test2>tttt</test2>
    <test3 ab="test" xvf="sample"><aa>sample</aa></test3>
  </info>
</record>
```

```scala
val schema = StructType(Array(
  StructField("title", StringType),
  StructField("info", StringType)
))

val sample = spark.read.format("com.databricks.spark.xml").option("rowTag", "record").schema(schema).load("temp/sample.xml")

sample.show(false)
```

result,
```txt
+-----------------+---------------------------------------------------------------------+
|title            |info                                                                 |
+-----------------+---------------------------------------------------------------------+
|hihihihi & tttt  |<test1>test_</test1><test2>tttt</test2><test3><aa>sample</aa></test3>|
+-----------------+---------------------------------------------------------------------+
```

info value expected,
```txt
<test1>test_</test1><test2>tttt</test2><test3 ab="test" xvf="sample"><aa>sample</aa></test3>
```

How can I get nested xml text completely?

**Comment by srowen** [comment] 2019-01-09 13:50
Duplicate of #340 , or related I think

**Comment by srowen** [comment] 2019-01-21 14:49
Oh, aren't you missing the attributes from the schema you provided? the result looks correct given the schema

**Comment by Jeongmin-Lee** [comment] 2019-01-23 14:22
Specifying all the schemas is not a problem. However, my purpose is to extract nested xml text.
To do this, I have specified a schema as shown below.

```scala
...
StructField("info", StringType)
...
```

But, when extracting xml text nested in the `info` tag, attributes of the `test3` tag are not visible.

expected this.
```xml
<test3 ab="test" xvf="sample"><aa>sample</aa></test3>
```

but result,

```xml
<test3><aa>sample</aa></test3>
```

**Comment by srowen** [comment] 2019-01-23 15:15
Try inferring the schema to see what schema would correspond to extracting the attribute values. You don't have schema elements for those attributes and I think that's the issue.

**Comment by Magudeswaran-R** [comment] 2019-07-31 05:18
Hi Team..i am also facing the same issue..where in the same worked as expected by @Jeongmin-Lee ..it will be very helpful if there is any other way to fix it

**Closed** 2020-08-24 16:04 UTC
Labels: bug
