### ISSUE TITLE
Inconsistent element attributes

### ISSUE THREAD

**Issue by cjmatta** [databricks/spark-xml#93] opened 2016-02-19 20:28 UTC
I have a question about the behavior of this code when presented with a document such as this:
```xml
<library location="uptown">
    <shelf category="fiction">
        <book author="Lewis Carol">Alice's Adventures In Wonderland</book>
        <book author="James Joyce">Portrait of the Artist as a Young Man</book>
    </shelf>
    <shelf category="non-fiction">
        <book author="Carl Sagan">Billions and Billions</book>
        <book>Webster's Collegiate Dictionary</book>
    </shelf>
</library>
<library location="downtown">
    <shelf category="fiction">
        <book author="J.K. Rowling">Harry Potter and the Prisoner of Azkaban</book>
        <book author="Homer">The Iliad</book>
    </shelf>
    <shelf category="non-fiction">
        <book author="Stephen Hawking">A Brief History of Time</book>
        <book author="Benjamin Franklin">The Autobiography of Benjamin Franklin</book>
    </shelf>
</library>
```
As you can see there's a book in there without an `author` attribute.

I can load this xml and print the schema:
```
val test = sqlContext.read.format("com.databricks.spark.xml").option("rowTag", "library").load("maprfs:///user/cmatta/projects/test.xml")
test.printSchema

test: org.apache.spark.sql.DataFrame = [@location: string, shelf: array<struct<@category:string,book:array<struct<#VALUE:string,@author:string>>>>]
root
 |-- @location: string (nullable = true)
 |-- shelf: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- @category: string (nullable = true)
 |    |    |-- book: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- #VALUE: string (nullable = true)
 |    |    |    |    |-- @author: string (nullable = true)
```

If I want to select all the books by location and collect them I get a `java.lang.ArrayIndexOutOfBoundsException: 1` error. If I just collect the whole dataframe without select I can see that the "Webster's Collegiate Dictionary" book array only has one element, where I would have expected two: the value and a null representing the author. Is this a correct expectation?
```
test.collect
res552: Array[org.apache.spark.sql.Row] = Array([uptown,WrappedArray([fiction,WrappedArray([Alice's Adventures In Wonderland,Lewis Carol], [Portrait of the Artist as a Young Man,James Joyce])], [non-fiction,WrappedArray([Billions and Billions,Carl Sagan], [Webster's Collegiate Dictionary])])], [downtown,WrappedArray([fiction,WrappedArray([Harry Potter and the Prisoner of Azkaban,J.K. Rowling], [The Iliad,Homer])], [non-fiction,WrappedArray([A Brief History of Time,Stephen Hawking], [The Autobiography of Benjamin Franklin,Benjamin Franklin])])])
```

If this behavior is expected, what's the best way to deal with inconsistent XML like this?

**Comment by HyukjinKwon** [comment] 2016-02-21 04:04
@cjmatta thenks for reporting this. I will look into this further.

**Comment by larsbkrogvig** [comment] 2016-02-21 12:19
Maybe this can help to track down the root cause: https://issues.apache.org/jira/browse/SPARK-12624

Apparently a `java.lang.ArrayIndexOutOfBoundsException` is thrown when row lengths do not match.

**Comment by HyukjinKwon** [comment] 2016-02-24 09:20
I see. Good niches. I think I should set `null` explicitly for the fields as well just like the other fields. This will be quicky fix. I will fix this tomorrow.

**Comment by HyukjinKwon** [comment] 2016-03-03 04:48
Fixed in https://github.com/databricks/spark-xml/pull/95.

**Closed by HyukjinKwon** 2016-03-03 04:48 UTC
Labels: bug
