### ISSUE TITLE
Values not being parsed correctly / showing as null 

### ISSUE THREAD

**Issue by spiu** [databricks/spark-xml#88] opened 2016-02-15 15:57 UTC
Hi,

I've noticed that some fields in an xml I'm parsing come up as `null`. I'm using the code from master (updated as of today) and Schema generation seems to be alright.

It seems to be a problem in `StaxXmlParser` sending an incorrect "sub-schema". But I could not get to the root of the problem yet.

Any ideas on what could be wrong?

[Sample file here](https://github.com/databricks/spark-xml/files/131037/fpml-sample.xml.txt)

```
<dtcc:genericProductDTCC id="Id_12345">
    <fpml:primaryAssetClass>Equity</fpml:primaryAssetClass>
    <fpml:productType productTypeScheme="urn:bank:product-type:isda-plus">Equity:Exotic:Option</fpml:productType>
    <fpml:productId productIdScheme="http://www.fpml.org/coding-scheme/product-taxonomy">Equity:Other</fpml:productId>
    <fpml:productId productIdScheme="http://www.dtcc.com/coding-scheme/Narrow-Broad-Id">Broad</fpml:productId>
    <fpml:embeddedOptionType>false</fpml:embeddedOptionType>
    <fpml:buyerPartyReference href="party1"></fpml:buyerPartyReference>
    <fpml:buyerAccountReference href="account1"></fpml:buyerAccountReference>
    <fpml:sellerPartyReference href="party2"></fpml:sellerPartyReference>
    <fpml:premium>
        <fpml:payerPartyReference href="party1"/>
        <fpml:payerAccountReference href="account1"/>
        <fpml:receiverPartyReference href="party2"/>
        <fpml:paymentAmount>
            <fpml:currency>USD</fpml:currency>
            <fpml:amount>0</fpml:amount>
        </fpml:paymentAmount>
        <fpml:paymentDate>
            <fpml:adjustableDate>
                <fpml:unadjustedDate>2014-10-28</fpml:unadjustedDate>
            </fpml:adjustableDate>
        </fpml:paymentDate>
    </fpml:premium>
    <fpml:effectiveDate>
        <fpml:unadjustedDate>2014-10-24</fpml:unadjustedDate>
    </fpml:effectiveDate>
    <fpml:expirationDate>
        <fpml:unadjustedDate>2016-10-21</fpml:unadjustedDate>
    </fpml:expirationDate>
    <fpml:underlyer>
        <fpml:basket>
            <fpml:openUnits>999</fpml:openUnits>
            <fpml:basketConstituent>
                <fpml:index id="ULId_67158430_843509334">
                    <fpml:instrumentId instrumentIdScheme="http://www.fpml.org/coding-scheme/external/instrument-id-Reuters-RIC">.SPX</fpml:instrumentId>
                    <fpml:exchangeId exchangeIdScheme="http://www.fpml.org/coding-scheme/external/exchange-id-MIC">NYSE</fpml:exchangeId>
                </fpml:index>
                <fpml:constituentWeight>
                    <fpml:basketPercentage>1</fpml:basketPercentage>
                </fpml:constituentWeight>
            </fpml:basketConstituent>
        </fpml:basket>
    </fpml:underlyer>
    <fpml:notional>
        <fpml:currency>USD</fpml:currency>
        <fpml:amount>1100000</fpml:amount>
    </fpml:notional>
    <fpml:optionType>Call</fpml:optionType>
    <fpml:settlementCurrency>USD</fpml:settlementCurrency>
    <dtcc:genericProductExtension>
        <dtcc:exerciseStyleEnum>European</dtcc:exerciseStyleEnum>
        <dtcc:settlementTypeEnum>Cash</dtcc:settlementTypeEnum>
        <dtcc:strike>
            <fpml:strikePercentage>104.615</fpml:strikePercentage>
            <fpml:currency>USD</fpml:currency>
        </dtcc:strike>
        <dtcc:optionCommencementDate>
            <fpml:adjustableDate>
                <fpml:unadjustedDate>2014-10-24</fpml:unadjustedDate>
            </fpml:adjustableDate>
        </dtcc:optionCommencementDate>
        <dtcc:paymentFrequency/>
    </dtcc:genericProductExtension>
</dtcc:genericProductDTCC>
```

Sample output:
```
scala> df.select("tradeEvent.trade.dtcc:genericProductDTCC.*").show(true)
+--------+----------------------------+--------------------------+------------------------+------------------+-----------------------+-------------------+-------------+---------------+------------+----------------------+--------------------+--------------------+-------------------------+-----------------------+--------------+
|     @id|dtcc:genericProductExtension|fpml:buyerAccountReference|fpml:buyerPartyReference|fpml:effectiveDate|fpml:embeddedOptionType|fpml:expirationDate|fpml:notional|fpml:optionType|fpml:premium|fpml:primaryAssetClass|      fpml:productId|    fpml:productType|fpml:sellerPartyReference|fpml:settlementCurrency|fpml:underlyer|
+--------+----------------------------+--------------------------+------------------------+------------------+-----------------------+-------------------+-------------+---------------+------------+----------------------+--------------------+--------------------+-------------------------+-----------------------+--------------+
|Id_12345|                        null|                      null|                    null|              null|                   null|               null|         null|           null|        null|                Equity|[[null,http://www...|[Equity:Exotic:Op...|                     null|                   null|          null|
+--------+----------------------------+--------------------------+------------------------+------------------+-----------------------+-------------------+-------------+---------------+------------+----------------------+--------------------+--------------------+-------------------------+-----------------------+--------------+
```

```
scala> df.select("tradeEvent.trade.dtcc:genericProductDTCC.fpml:buyerAccountReference.*").show(true)
+------+-----+
|#VALUE|@href|
+------+-----+
|  null| null|
+------+-----+


```

**Comment by HyukjinKwon** [comment] 2016-02-16 02:36
@spiu Due to structure conversion, it brings a lot of complexities so it will be tricky to find the root problem. Anyway I think this is an issue. I will also look into this deeper.

**Comment by HyukjinKwon** [comment] 2016-02-16 09:50
As it is confirmed according to his comment, https://github.com/databricks/spark-xml/pull/89#issuecomment-184586520, I am closing this.

**Closed by HyukjinKwon** 2016-02-16 09:50 UTC
Labels: bug
