### ISSUE TITLE
Unable to read xml files under « partition directory »

### ISSUE THREAD

**Issue by LvffY** [databricks/spark-xml#496] opened 2020-10-29 08:38 UTC
Hello, 

I'm trying to read XML files with your API and I'm get stuck with a problem I don't find any solution.

I would like to read XML files like other CSV files with `basePath` option. 

- I have some input files under `/input/dhi=20201029120000/data.csv` and `/input/dhi=20201029130000/data.csv`. `data.csv` is as follow: 
<details>
  <summary>Click to see data</summary>

```csv
id1
id2
```
</details>

- When i'm running this command : 

```scala
val paths = Seq("/input/dhi=20201029120000/data.csv", "/input/dhi=20201029130000/data.csv")
spark.read.option("basePath", "/input").csv(paths: _*).show(false)
```

- I get the following output

```console
+---+--------------+
|id |dhi           |
+---+--------------+
|id1|20201029120000|
|id2|20201029120000|
|id1|20201029130000|
|id2|20201029130000|
+---+--------------+
```

As long as I know, your API can't be called like `spark.read.xml(paths: _*)` (may be causing by #4 ?)

Now if i'm adapting this to my XML files : 

- I have some input files under `/input/dhi=20201029120000/data.xml` and `/input/dhi=20201029130000/data.xml`. `data.xml` is as follow : 

<details>
  <summary>Click to see data</summary>

```xml
<datas>
    <data>
        <id>id1</id>
    </data>
    <data>
        <id>id2</id>
    </data>
    <data>
        <id>id3</id>
    </data>
</datas>
```
</details>

- When I'm running this command : 

```scala
val paths = Seq("/input/dhi=20201029120000/data.xml", "/input/dhi=20201029130000/data.xml")
spark.read.options(Map("basePath" ->"/input", "rootTag" -> "datas", "rowTag" -> "data")).xml(paths.mkString(",")).show(false)
```

- I'm getting the following ouput (i.e i'm missing the « partition » directory `dhi`)

```console
+---+
|id |
+---+
|id1|
|id2|
|id1|
|id2|
+---+
```

- When I'm running this command : 

```scala
val paths = Seq("/input/dhi=20201029120000/data.xml", "/input/dhi=20201029130000/data.xml")
spark.read.options(Map("basePath" ->"/input", "rootTag" -> "datas", "rowTag" -> "data")).format("xml").load(paths: _*).show(false)
```

- I'm getting an Exception with message `'path' must be specified for XML data.`

I'm already using this method with CSV and JSON files (I suppose this works with all spark-native datasources) and it could be very cool to have it work on XML files too ! 

Please tell me if I'm missing something, if you have a workaround or any other questions ! 

Thanks !

**Comment by srowen** [comment] 2020-10-29 13:56
I think you're right, it doesn't work, and yes probably has to do with DSv2 support. That I don't know how to change/fix but would be open to anyone trying. Do wildcards work in a single path? `.../**/**` or `.../*/*`?

**Comment by LvffY** [comment] 2020-10-31 07:55
No wilcards doesn't work :( 

I'll have to wait that someone gets interestes into this problem unfortunately :(

**Comment by srowen** [comment] 2020-11-16 14:30
I am provisionally closing this as a likely duplicate of #4 as you note. Yes it would be good to allow that to work.

**Closed by srowen** 2020-11-16 14:30 UTC
