### ISSUE TITLE
Writing XML header in output

### ISSUE THREAD

**Issue by abhilashbhattacharya** [databricks/spark-xml#315] opened 2018-07-05 06:59 UTC
Would like to know how can i add an XML header as 
\<?xml version = "1.0" encoding = "UTF-8" ?\>. Can someone help me out how to add this.

**Comment by abhilashbhattacharya** [comment] 2018-07-05 07:03
<?xml version = "1.0" encoding = "UTF-8" ?>

**Comment by punithmailme** [comment] 2018-07-10 04:35
@abhilashbhattacharya  which version of spark are you using ?

**Comment by punithmailme** [comment] 2018-07-10 04:38
@abhilashbhattacharya i am facing an issue where i cannot generate a xml with spark 2.1.2 and spark-xml 0.4.1.. when i run it as a main program i can generate it. but when i submit it as a spark job it fails with XMLStreamException... Can you please help.

**Comment by srowen** [comment] 2018-12-21 13:53
Duplicate of #278

**Closed by srowen** 2018-12-21 13:53 UTC
