### ISSUE TITLE
How to remove 'ROWS' while writing XML, I am using only 'rowTag' in options..

### ISSUE THREAD

**Issue by naveenreddy2811** [databricks/spark-xml#219] opened 2016-12-16 09:47 UTC
I have below XML, 

`<SeriesDataExchang xmlns="XMLSchemas/SeriesDataExchang" xmlns:md="XMLSchemas/SeriesDataExchang">
	<md:Creator>user_1</md:Creator>
	<md:Date>2015-11-26</md:Date>
	<Station reference="11111" >
		<SetofValues qualifier="Stage">
			<Value time="16:15:00">0.56</Value>
			<Value time="16:30:00">0.64</Value>
		</SetofValues>
	</Station>
	<Station reference="22222">
		<SetofValues qualifier="landing">
			<Value time="16:15:00">1.4</Value>
			<Value time="16:30:00">1.6</Value>
		</SetofValues>
	</Station>
</SeriesDataExchang>`

when I am giving 'SeriesDataExchang' as 'rootTag' and 'Station' as 'rowTag' I am getting schema as below.

`val df = sqlContext.read.format("xml").option("rootTag", "SeriesDataExchang").option("rowTag", "Station").option("valueTag", "#VALUE").load(path)`

root
 |-- SetofValues: struct (nullable = true)
 |    |-- Value: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- #VALUE: double (nullable = true)
 |    |    |    |-- _time: string (nullable = true)
 |    |-- _qualifier: string (nullable = true)
 |-- _reference: string (nullable = true)

In schema I am not getting rootTag details and attributes, whhich are necessary. So I gave  root tag 'SeriesDataExchang' as 'rowTag' which give me all the elements including root tag attributes.
 
`val df = sqlContext.read.format("xml").option("rowTag", "SeriesDataExchang").option("valueTag", "#VALUE").load(path)`
 
 root
 |-- Station: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- SetofValues: struct (nullable = true)
 |    |    |    |-- Value: array (nullable = true)
 |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |-- #VALUE: double (nullable = true)
 |    |    |    |    |    |-- _time: string (nullable = true)
 |    |    |    |-- _qualifier: string (nullable = true)
 |    |    |-- _reference: string (nullable = true)
 |-- _md: string (nullable = true)
 |-- _xmlns: string (nullable = true)
 |-- md:Creator: string (nullable = true)
 |-- md:Date: string (nullable = true)

When i am giving 'rowTag' alone to write dataframe as xml using below command.

`df.repartition(1).write.format("xml").option("rowTag","SeriesDataExchang").option("valueTag", "#VALUE").save(path)`

which gives below output.
`<ROWS>
	<SeriesDataExchang md="XMLSchemas/SeriesDataExchang" xmlns="XMLSchemas/SeriesDataExchang">
		<Station stationReference="11111">
			<SetofValues qualifier="Stage">
				<Value time="16:15:00">0.56</Value>
				<Value time="16:30:00">0.64</Value>
			</SetofValues>
		</Station>
		<Station stationReference="22222">
			<SetofValues qualifier="landing">
				<Value time="16:15:00">1.4</Value>
				<Value time="16:30:00">1.6</Value>
			</SetofValues>
		</Station>
		<md:Creator>user_1</md:Creator>
		<md:Date>2015-11-26</md:Date>
	</SeriesDataExchang>
</ROWS>` 

When i am giving both 'rootTag' and 'rowTag' to write dataframe as xml using below command.

`df.repartition(1).write.format("xml").option("rootTag","SeriesDataExchang").option("rowTag","Station").option("valueTag", "#VALUE").save(path)`

which gives below output
`<SeriesDataExchang>
    <Station md="XMLSchemas/SeriesDataExchang" xmlns="XMLSchemas/SeriesDataExchang">
        <Station stationReference="11111">
            <SetofValues qualifier="Stage">
                <Value time="16:15:00">0.56</Value>
                <Value time="16:30:00">0.64</Value>
            </SetofValues>
        </Station>
        <Station stationReference="22222">
            <SetofValues qualifier="landing">
                <Value time="16:15:00">1.4</Value>
                <Value time="16:30:00">1.6</Value>
            </SetofValues>
        </Station>
        <md:Creator>user_1</md:Creator>
        <md:Date>2015-11-26</md:Date>
    </Station>
</SeriesDataExchang>`

I am expecting output to be as below.
`<SeriesDataExchang md="XMLSchemas/SeriesDataExchang" xmlns="XMLSchemas/SeriesDataExchang">
	<Station stationReference="11111">
		<SetofValues qualifier="Stage">
			<Value time="16:15:00">0.56</Value>
			<Value time="16:30:00">0.64</Value>
		</SetofValues>
	</Station>
	<Station stationReference="22222">
		<SetofValues qualifier="landing">
			<Value time="16:15:00">1.4</Value>
			<Value time="16:30:00">1.6</Value>
		</SetofValues>
	</Station>
	<md:Creator>user_1</md:Creator>
	<md:Date>2015-11-26</md:Date>
</SeriesDataExchang>`

Let me know if we can achieve this using 'rowTag' and 'rootTag'.

**Comment by HyukjinKwon** [comment] 2016-12-16 09:50
Oh, I see. It seems a bug due to structure conversion between XML and dataframe.

**Comment by HyukjinKwon** [comment] 2016-12-16 10:06
(note to myself) loosely related with https://github.com/databricks/spark-xml/issues/213, in particular the suggestion, https://github.com/databricks/spark-xml/issues/213#issuecomment-264472359

**Comment by naveenreddy2811** [comment] 2016-12-16 13:24
I am able to retrieve root element attributes by making root element as rowTag option... if I am doing same While writing I am getting ROWS as as root element....  As per my dataframe schema if I could remove '<ROWS> </ROWS>' from file that would help.. Is there any option to avoid writing <ROWS> </ROWS>.

**Comment by HyukjinKwon** [comment] 2016-12-16 13:29
I am sorry for asking this but.. I think I could not understand clearly this sentence 

> As per my dataframe schema if I could remove ' ' from file that 

Could I please ask to elaborate this a bit more?

**Comment by naveenreddy2811** [comment] 2016-12-16 14:39
Sorry, missed this line... 
`<ROWS> </ROWS>`.

Is there any option to avoid writing `<ROWS> </ROWS>`

**Comment by naveenreddy2811** [comment] 2017-01-02 11:46
@HyukjinKwon Can we add something like below as an option for write dataframe to XML.

`val rootTagReq = parameters.getOrElse("rootTagReq", XmlOptions.DEFAULT_ROOT_TEST)
 var indentedXml = ""
 if (rootTagReq.toUpperCase().equals("NO")){
     firstRow = false
     lastRow = false
     indentedXml = xml
 } else {
      indentedXml = indent + xml.replaceAll(rowSeparator, rowSeparator + indent)
 }`

adding above option works for my scenario..

**Comment by tacareyNBC** [comment] 2017-08-21 21:01
Is there anyway to add attributes to the root tag?

**Comment by tacareyNBC** [comment] 2017-08-21 21:01
@HyukjinKwon - Is there any way to add attributes to the root tag?

**Comment by HyukjinKwon** [comment] 2018-12-22 10:46
This is a duplicate of #128. Let's don't fix this - we won't be able to read it back.

**Closed by HyukjinKwon** 2018-12-22 10:46 UTC
Labels: bug
