### ISSUE TITLE
Log shows error even though it's catched

### ISSUE THREAD

**Issue by maarest** [databricks/spark-xml#111] opened 2016-04-19 05:36 UTC
Take the following XML

```
<Root>
   <RowTag1>
      <col1>foo</col1>
   </RowTag1>
   <RowTag2>
      <RowTag1>foo3</RowTag1>
   </RowTag2>
</Root>
```

If you do 
```
val dfTry = Try(sqlContext.read
      .format("xml")
      .option("rowTag", "RowTag1")
      .load(path))
```

Then I wouldn't expect to see this log (the code still executes fine... but I don't want to see this error message because I have it surrounded in Try)

> 16/04/19 15:34:55 ERROR Executor: Exception in task 0.0 in stage 15.0 (TID 30)
> scala.MatchError: null
> 	at com.databricks.spark.xml.parsers.StaxXmlParserUtils$.checkEndElement(StaxXmlParserUtils.scala:25)
> 	at com.databricks.spark.xml.util.InferSchema$.com$databricks$spark$xml$util$InferSchema$$inferObject(InferSchema.scala:198)
> 	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:92)
> 	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:83)
> 	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
> 	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
> 	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1194)
> 	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:212)
> 	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1194)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1099)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1099)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1100)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1100)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:88)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 16/04/19 15:34:55 ERROR TaskSetManager: Task 0 in stage 15.0 failed 1 times; aborting job
> 16/04/19 15:34:59 ERROR Executor: Exception in task 0.0 in stage 40.0 (TID 70)
> scala.MatchError: null
> 	at com.databricks.spark.xml.parsers.StaxXmlParserUtils$.checkEndElement(StaxXmlParserUtils.scala:25)
> 	at com.databricks.spark.xml.util.InferSchema$.com$databricks$spark$xml$util$InferSchema$$inferObject(InferSchema.scala:198)
> 	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:92)
> 	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:83)
> 	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
> 	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
> 	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1194)
> 	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:212)
> 	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1194)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1099)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1099)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1100)
> 	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1100)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:88)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 16/04/19 15:34:59 ERROR TaskSetManager: Task 0 in stage 40.0 failed 1 times; aborting job

FYI this code:
```
    val tryStuff = Try(throw new IllegalArgumentException("sample exception..."))
    System.exit(1)
```
is silent

**Comment by Bertrandbenj** [comment] 2016-04-19 08:59
I can confirm this is an issue, I've got the same (if the rowTag's name appear in two different places)

should we have a rowTag expressed as an xpath instead to avoid this problem or do you have a programmatic solution 

.option("rowTag", "/Root/RowTag1") ? 

what if the expected behavior is to get RowTag1 no matter its position (case which seems less likely but can happen). I think the issue is here but there is different solutions. 

<Root>
   <RowTag1>
      <col1>foo</col1>
   </RowTag1>
   <RowTag2>
      <RowTag1>foo3</RowTag1>
   </RowTag2>
</Root>

**Comment by HyukjinKwon** [comment] 2016-04-27 04:09
@Bertrandbenj @maarest  Indeed. I noticed this problem but could not come up with a great solution. Please feel free to suggest a solution. I will try to think about this too.

**Comment by HyukjinKwon** [comment] 2016-09-09 10:35
This should be fixed in https://github.com/databricks/spark-xml/pull/161. Please feel free to re-open if this is still not resolved. Thank you all!

**Closed by HyukjinKwon** 2016-09-09 10:35 UTC
Labels: bug
