### ISSUE TITLE
Using SAX instead of DOM for type inference and Row conversion

### ISSUE THREAD

**Issue by rxin** [databricks/spark-xml#3] opened 2015-11-26 06:08 UTC
Building a full DOM tree for each XML record is very expensive and unnecessary, since we only need to traverse the contents once for either type inference or Row conversion. Using SAX can probably win much better performance.

Link from https://github.com/HyukjinKwon/spark-xml/issues/8

**Comment by HyukjinKwon** [comment] 2015-11-26 06:49
For this issue, I got a reason to use DOM. Mostly the main reason is to infer ArrayType. In order to infer ArrayType, it needs to check all the child keys (child elements) in each record in a XML and decide it is a StructType when it has a single key or ArrayType when it has duplicated multiple keys.

(I also manually gave a precedence for ArrayType higher than StructType at InferSchema in case that some records have a single key (field) A, namely inferred as StructType, while others can have duplicated multiple keys (fields) A, namely inferred as ArrayType, where key (field) A should be inferred as ArrayType)

At the first I used StAX, but I realised that the implementation actually works almost like DOM (It just read all the elements for a record first and then started to process). So I changed it to DOM #2.

Maybe there is another clever way but I could not come up with one. It would be great if there is a good way to resolve the problem with SAX.

I think anyway it can use SAX for constructing Rows as the problem is only about type inference.

Link from https://github.com/HyukjinKwon/spark-xml/issues/8#issuecomment-159764517

**Comment by HyukjinKwon** [comment] 2015-12-21 23:35
Ah. Actually I think I can do this reducing `ObjectType` having the smae fields to `ArrayType` after inferring types for each. I will try.

**Comment by HyukjinKwon** [comment] 2016-01-07 08:47
Fixed in https://github.com/databricks/spark-xml/pull/43.

**Closed by HyukjinKwon** 2016-01-07 08:47 UTC
Labels: enhancement

**Comment by HyukjinKwon** [comment] 2016-01-07 08:53
I used StAX parser instead of SAX because I can easily resample JSON datasource in Spark which uses Jackson parser (pull model). Since the issue was not to build a full DOM tree but to traverse the contents once, I anyway closed this issue.
