### ISSUE TITLE
Flattening XML in a DataFrame

### ISSUE THREAD

**Issue by srikanthjella** [databricks/spark-xml#155] opened 2016-08-21 20:49 UTC
I am trying flatten variety of XMLs using DataFrames. I’m using spark-xml package which is automatically inferring my schema and creating a DataFrame. 

I do not want to hard code any XPaths in DataFrame as I do not know the tag name before hand and each might be lot more depth. I simply want to flatten any type of XML and then write output data to a hive table.

Example XML and expected output is given below.

Sample XML:
`<emplist>
<emp>
   <manager>
   <id>1</id>
   <name>foo</name>
    <subordinates>
      <clerk>
        <cid>1</cid>
        <cname>foo</cname>
      </clerk>
      <clerk>
        <cid>1</cid>
        <cname>foo</cname>
      </clerk>
    </subordinates>
   </manager>
</emp>
</emplist>
`

Expected output:
id, name, clerk.cid, clerk.cname
1, foo, 2, cname2
1, foo, 3, cname3

**Comment by HyukjinKwon** [comment] 2016-08-22 00:17
I see. Is this related with https://github.com/databricks/spark-xml/issues/91?

**Comment by HyukjinKwon** [comment] 2016-12-27 09:56
I am closing this for now. It seems a duplicate of it. Please feel free to reopen if you think this is a different issue with this.

**Closed by HyukjinKwon** 2016-12-27 09:56 UTC
Labels: duplicate
