### ISSUE TITLE
Cannot read stackoverflow data dump XML

### ISSUE THREAD

**Issue by ebuildy** [databricks/spark-xml#109] opened 2016-04-16 21:55 UTC
I would like to parse XML from stackoverflow data dump, here an example of row:

``` xml
<row Id="7" PostTypeId="2" ParentId="4" CreationDate="2008-07-31T22:17:57.883" Score="287" Body="An explicit cast to double isn't necessary." OwnerUserId="9" LastEditorUserId="967315" LastEditDate="2012-10-14T11:50:16.703" LastActivityDate="2012-10-14T11:50:16.703" CommentCount="0" />
```

But loading this XML, nothing happen (no error, and schema is empty), is it compatible with this library?

Thanks you,

**Comment by HyukjinKwon** [comment] 2016-04-17 02:17
To be clear, it is a duplicate of https://github.com/databricks/spark-xml/issues/92 but thanks for some cases I would definitely try.

**Comment by ebuildy** [comment] 2016-04-17 06:57
D'oh sorry for the duplicate issue, didn't find it yesterday. Do you want to me to close this issue?

Thanks you,

**Comment by HyukjinKwon** [comment] 2016-04-17 07:03
I think it is fine. I think it is a good reminder to test stackoverflow data dump.

**Comment by queirozfcom** [comment] 2017-04-27 23:45
I still can't parse the dump. I think this is related to https://github.com/databricks/spark-xml/issues/190.

**Comment by BioQwer** [comment] 2018-12-04 18:50
fix in #321

**Closed** 2018-12-19 22:52 UTC
Labels: enhancement
