### ISSUE TITLE
spark-xml partitioning multiple xml.gz files

### ISSUE THREAD

**Issue by ayat-khairy** [databricks/spark-xml#264] opened 2017-08-09 11:09 UTC
Hi,

I am trying to parse 130,000 .xml.gz files using spark-xml. After loading the data, Spark always creates 130,000 partitions (the number of files). However, this slows down the performance as each file size is small and having less number of partitions is better. I tried to repartition the dataframe in which the data loaded several times but it does not work and the number of partitions is always equals to the number of files.

How can I solve that? ... Thanks

![image](https://user-images.githubusercontent.com/2110822/29118831-8ff40948-7cfb-11e7-9c9d-397460124cd9.png)

**Comment by HyukjinKwon** [comment] 2017-11-04 08:39
Spark has an optimisation about it for file based data sources as far as I remember. Probably, it's a duplicate of https://github.com/databricks/spark-xml/issues/4 to enable this optimization. Let'a close this for now. I plan to resolve it soon.

**Closed by HyukjinKwon** 2017-11-04 08:39 UTC
