### ISSUE TITLE
Failed to load spark xml for Spark 2.0.1

### ISSUE THREAD

**Issue by VishnuVR1988** [databricks/spark-xml#202] opened 2016-11-05 12:58 UTC
I have started shell using the command
**spark-shell --packages com.databricks:spark-xml_2.11:0.4.0**

While i am trying to load a file using spark.xml, i am getting the below error

```
scala> sqlContext.read.format("com.databricks.spark.xml").load("cars-no-indentation.xml")
java.lang.ClassNotFoundException: Failed to find data source:com.databricks.spark.xml. Please find packages at https://cwiki.apache.org/confluence/display/SPARK/Third+Party+Projects
  at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:148)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:79)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:79)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
```

**Comment by HyukjinKwon** [comment] 2016-11-06 10:35
Hm.. it seems working fine with me.

**Comment by VishnuVR1988** [comment] 2016-11-06 12:49
I am running spark-shell on Windows 10 and also i am using the latest spark distribution.

**Comment by Sokrates80** [comment] 2016-11-06 13:15
I guess you need to download and copy winutils.exe in the right path:
https://jaceklaskowski.gitbooks.io/mastering-apache-spark/content/spark-tips-and-tricks-running-spark-windows.html

**Comment by HyukjinKwon** [comment] 2016-11-23 00:38
I am closing this. The exception messages exactly refers that the jar could not be found. If any of you is pretty sure that it is an issue in this library, please feel free to open another one or duplicate of this issue.

**Closed by HyukjinKwon** 2016-11-23 00:38 UTC
