### ISSUE TITLE
Incomplete values for some tags

### ISSUE THREAD

**Issue by humanzz** [databricks/spark-xml#81] opened 2016-02-08 15:27 UTC
I'm trying to read the english wikipedia data dump using spark-xml. My setup is as follows:
- zeppelin 0.5.6 (using built it Spark 1.6.0)
- using spark-xml 0.3.1 on scala 2.10

I'm loading the wikipedia pages as follows
`val items = z.sqlContext.read`
`                        .format("com.databricks.spark.xml")`
`                        .option("rowTag", "page")`
`                        .load("<PATH>/enwiki-latest-pages-articles-sample.xml")`

which succeeds and infers a schema that seems reasonable
`org.apache.spark.sql.DataFrame = [id: bigint, ns: bigint, redirect: struct<#VALUE:string,@title:string>, revision: struct<comment:string,contributor:struct<id:bigint,ip:string,username:string>,format:string,id:bigint,minor:string,model:string,parentid:bigint,sha1:string,text:struct<#VALUE:string,@space:string>,timestamp:string>, title: string]`

If I try to `items.select("revision.text.#VALUE")` it gives me a value that's only a prefix to the whole text available in that page meaning the value is not read fully.

Another thing I tried is to do 
`// changing the rowTag from page to text`
`val items = z.sqlContext.read`
`                        .format("com.databricks.spark.xml")`
`                        .option("rowTag", "text")`
`                        .load("<PATH>/enwiki-latest-pages-articles-sample.xml")`

and I now get
`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 4, localhost): scala.MatchError: ENDDOCUMENT (of class com.sun.xml.internal.stream.events.EndDocumentEvent)`
`	at com.databricks.spark.xml.parsers.StaxXmlParser$.checkEndElement(StaxXmlParser.scala:94)`
`	at com.databricks.spark.xml.util.InferSchema$.com$databricks$spark$xml$util$InferSchema$$inferObject(InferSchema.scala:218)`
`	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:95)`
`	at com.databricks.spark.xml.util.InferSchema$$anonfun$3$$anonfun$apply$2.apply(InferSchema.scala:83)`
`	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)`
`...`

which seems to suggest that for some reason it's not able to find the end_tag for text even though it is there.

I'm assuming something is wrong with the XML parsing here but I'm not really sure what's special abt the text tag.

I've attached the input file at https://gist.github.com/humanzz/e2e296fd82dccaa5109c

**Comment by humanzz** [comment] 2016-02-08 16:03
using the current spark-xml snapshot (spark-xml_2.10-0.3.2-SNAPSHOT.jar) seems to have loaded the full context of the text tag.

However,
`// changing the rowTag from page to text`
`val items = z.sqlContext.read`
`                        .format("com.databricks.spark.xml")`
`                        .option("rowTag", "text")`
`                        .load("<PATH>/enwiki-latest-pages-articles-sample.xml")`
still fails. Maybe deeper level tags cannot be used as rowTags? I'm not sure what's the intended behaviour here.

**Comment by HyukjinKwon** [comment] 2016-02-09 12:56
@humanzz As far as I remember this was fixed in master branch but a release has been not published. I will try to reproduce this first with the master branch one. Thanks for reporting this.

**Comment by sgvandijk** [comment] 2016-02-09 14:36
I am running into `scala.MatchError: ENDDOCUMENT`. For me it seems because my input contains self-closing row tags, e.g. `<ROW attr="foo" />`. I see some self-closing tags in your input too, but not for your `text` row tag, so I don't know if it's the same problem.

@HyukjinKwon Is self-closing tags something that you want to support? I had a quick look and don't directly see a quick way to do that with how `XmlInputFormat` currently works. If you do I can open a separate issue for it.

**Comment by humanzz** [comment] 2016-02-09 14:39
@HyukjinKwon I confirm it's fixed in master branch. Just tried it yesterday.

I was running the spark-xml on a sample of a few wikipedia pages in the dump... I'm currently trying to read the whole dump **enwiki-latest-pages-articles.xml.bz2** but now failing with `scala.MatchError` in `com.databricks.spark.xml.parsers.StaxXmlParser$$anonfun$com$databricks$spark$xml$parsers$StaxXmlParser$$convertObject$1.apply$mcVI$sp(StaxXmlParser.scala:218)`.

As I'm no expert on spark internals, Is there a way to try the spark-xml reading independently so that I can reproduce the error but with more details this time?

**Comment by HyukjinKwon** [comment] 2016-02-11 02:10
@sgvandijk Yes, this should be supported. Thanks for looking into this deep. Could you please create another issue for this? 

@humanzz Actually, I recently tested this library with the wiki dump (only a small dataset) and it looked fine but not with a large data set due to the lack of resources (or my laziness to set up a cluster in AWS). I think I should test it again with the file you just said.

Also, If you meant testing this within IDE such as IntelliJ or Eclipse, you can simply "open" this directory and some configurations would be automatically set up (but maybe you might have to install Scala 2.10.x or 2.11.x). And then, you can just run some tests codes in `XmlSuite` within the IDE. This is what I usually do.

Alternatively, you can build this by `sbt package` and then start the `spark-shell` including the built jar file by `--jars`.

**Comment by HyukjinKwon** [comment] 2016-02-11 02:28
@humanzz Maybe the issue you just met is related with https://github.com/databricks/spark-xml/issues/80. I will try to resolve that one first.

**Comment by HyukjinKwon** [comment] 2016-02-15 01:46
@humanzz Would you please try this with 0.3.2? I just released a new one and it looks working fine with wiki dumps.

**Comment by humanzz** [comment] 2016-02-19 20:23
@HyukjinKwon Sorry for the late response. I just ran it today and it now works just fine :)

**Comment by HyukjinKwon** [comment] 2016-02-21 04:01
@humanzz thanks! I am closing this.

**Closed by HyukjinKwon** 2016-02-21 04:01 UTC
Labels: bug
