### ISSUE TITLE
Use an RDD or Dataframe column with raw xml content as input for spark-xml

### ISSUE THREAD

**Issue by someonehere15** [databricks/spark-xml#206] opened 2016-11-19 08:10 UTC
Would it be possible to load the raw xml text of the files (without parsing) directly onto an RDD with e.g. wholeTextFiles(), maybe even convert the RDD to dataframe, so each row would contain the raw xml text of a file, and then use the RDD values or a Dataframe column as input for spark-xml?

**UPDATE:**
So, I have some XML files that I need to load onto a Spark DataFrame using `spark-xml`.
However, I need to add some text into the XML files before they are parsed.

So I thought I can:

 1. load the files through `SparkContext.wholeTextFiles()` into an RDD, 
 2. (maybe convert to DataFrame), 
 3. do the modifications for each row containing the raw XML text matching each xml file, 
 4. use this RDD (or better DataFrame) containing the filename and raw XML text as a
    source for the input of `spark-xml`.

So I have an existing DataFrame containing the raw text of a file in each row, which is the equivalent of an actual file, and the DataFrame would be the equivalent of a folder.

I want to use this DataFrame as the input of `spark-xml`, or any Spark read operation for that matter. How can I do this (I'm using python)?

The problem is that the processing needs to remain distributed, so I can't just collect all the rows to the driver as a list and do everything there, because it would not be performant at all. So I have been trying to solve this by using this code:

    da = None 
    
    def addRow(rows):
        for row in rows:
            global da
            if da is None:
                with tempfile.NamedTemporaryFile(delete=False) as tf:
                    tf.write(row.CONTENT)
                    tf.seek(0)
                    da = session.read.load(tf.name, format='xml', rowTag='tag')
            else:
                with tempfile.NamedTemporaryFile(delete=False) as tf:
                    tf.write(row.CONTENT)
                    tf.seek(0)
                    da.unionAll(session.read.load(tf.name, format='xml', rowTag='tag'))
        return ''
             
    df.rdd.foreachPartition(addRow)

It was the only way I could find to get the RDD as an input to the spark-xml load call, considering it needs the filename initially. But I get the following error:

    Traceback (most recent call last):
      File "...\src\Hash.py", line 48, in <module>
        df.rdd.foreachPartition(addRow)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 767, in foreachPartition
        self.mapPartitions(func).count()  # Force evaluation
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 1008, in count
        return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 999, in sum
        return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 873, in fold
        vals = self.mapPartitions(func).collect()
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 776, in collect
        port = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 2403, in _jrdd
        self._jrdd_deserializer, profiler)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 2336, in _wrap_function
        pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\rdd.py", line 2315, in _prepare_for_python_RDD
        pickled_command = ser.dumps(command)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\serializers.py", line 428, in dumps
        return cloudpickle.dumps(obj, 2)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 657, in dumps
        cp.dump(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 107, in dump
        return Pickler.dump(self, obj)
      File "...\Python\Python35\lib\pickle.py", line 408, in dump
        self.save(obj)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 740, in save_tuple
        save(element)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 204, in save_function
        self.save_function_tuple(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 241, in save_function_tuple
        save((code, closure, base_globals))
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 725, in save_tuple
        save(element)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 770, in save_list
        self._batch_appends(obj)
      File "...\Python\Python35\lib\pickle.py", line 794, in _batch_appends
        save(x)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 204, in save_function
        self.save_function_tuple(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 241, in save_function_tuple
        save((code, closure, base_globals))
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 725, in save_tuple
        save(element)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 770, in save_list
        self._batch_appends(obj)
      File "...\Python\Python35\lib\pickle.py", line 794, in _batch_appends
        save(x)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 204, in save_function
        self.save_function_tuple(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 241, in save_function_tuple
        save((code, closure, base_globals))
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 725, in save_tuple
        save(element)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 770, in save_list
        self._batch_appends(obj)
      File "...\Python\Python35\lib\pickle.py", line 794, in _batch_appends
        save(x)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 204, in save_function
        self.save_function_tuple(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 241, in save_function_tuple
        save((code, closure, base_globals))
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 725, in save_tuple
        save(element)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 770, in save_list
        self._batch_appends(obj)
      File "...\Python\Python35\lib\pickle.py", line 797, in _batch_appends
        save(tmp[0])
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 204, in save_function
        self.save_function_tuple(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 241, in save_function_tuple
        save((code, closure, base_globals))
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 725, in save_tuple
        save(element)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 770, in save_list
        self._batch_appends(obj)
      File "...\Python\Python35\lib\pickle.py", line 797, in _batch_appends
        save(tmp[0])
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 198, in save_function
        self.save_function_tuple(obj)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 246, in save_function_tuple
        save(f_globals)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 810, in save_dict
        self._batch_setitems(obj.items())
      File "...\Python\Python35\lib\pickle.py", line 836, in _batch_setitems
        save(v)
      File "...\Python\Python35\lib\pickle.py", line 520, in save
        self.save_reduce(obj=obj, *rv)
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\cloudpickle.py", line 553, in save_reduce
        save(state)
      File "...\Python\Python35\lib\pickle.py", line 475, in save
        f(self, obj) # Call unbound method with explicit self
      File "...\Python\Python35\lib\pickle.py", line 810, in save_dict
        self._batch_setitems(obj.items())
      File "...\Python\Python35\lib\pickle.py", line 836, in _batch_setitems
        save(v)
      File "...\Python\Python35\lib\pickle.py", line 495, in save
        rv = reduce(self.proto)
      File "...\spark-2.0.1-bin-hadoop2.7\python\lib\py4j-0.10.3-src.zip\py4j\java_gateway.py", line 1133, in __call__
      File "...\spark-2.0.1-bin-hadoop2.7\python\pyspark\sql\utils.py", line 63, in deco
        return f(*a, **kw)
      File "...\spark-2.0.1-bin-hadoop2.7\python\lib\py4j-0.10.3-src.zip\py4j\protocol.py", line 323, in get_return_value
    py4j.protocol.Py4JError: An error occurred while calling o22.__getstate__. Trace:
    py4j.Py4JException: Method __getstate__([]) does not exist
    
    	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
    
    	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
    
    	at py4j.Gateway.invoke(Gateway.java:272)
    
    	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    
    	at py4j.commands.CallCommand.execute(CallCommand.java:79)
    
    	at py4j.GatewayConnection.run(GatewayConnection.java:214)
    
    	at java.lang.Thread.run(Unknown Source)

It appears I cannot do another RDD operation inside an RDD operation. Can anyone please help me, I don't know how to do this and I need a solution as soon as possible.

**Comment by MaciejGajewski** [comment] 2017-11-06 14:09
This is kind of ugly (unneccessary IO) but modified data frame can be written to xml files and then read once again via load function

**Comment by HyukjinKwon** [comment] 2018-12-22 10:45
This will be a duplicate of #322.

**Closed by HyukjinKwon** 2018-12-22 10:45 UTC
