### ISSUE TITLE
XmlInputFormat produces ArrayIndexOutOfBounds on compressed files

### ISSUE THREAD

**Issue by lokm01** [databricks/spark-xml#180] opened 2016-09-24 16:51 UTC
How to reproduce:
1) Use large XML file (e.g the protein file from http://www.cs.washington.edu/research/xmldatasets/www/repository.html#pir )
2) Modify to remove whitespace between the closing and opening row tags (e.g )
3) Compress with bz2

org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 123.0 failed 1 times, most recent failure: Lost task 1.0 in stage 123.0 (TID 131, localhost): java.lang.ArrayIndexOutOfBoundsException: 65536
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.hbCreateDecodeTables(CBZip2InputStream.java:666)
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.createHuffmanDecodingTables(CBZip2InputStream.java:793)
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.recvDecodingTables(CBZip2InputStream.java:765)
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.getAndMoveToFrontDecode(CBZip2InputStream.java:801)
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.initBlock(CBZip2InputStream.java:504)
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.changeStateToProcessABlock(CBZip2InputStream.java:333)
[info] at org.apache.hadoop.io.compress.bzip2.CBZip2InputStream.read(CBZip2InputStream.java:399)
[info] at org.apache.hadoop.io.compress.BZip2Codec$BZip2CompressionInputStream.read(BZip2Codec.java:483)
[info] at org.apache.hadoop.io.compress.BZip2Codec$BZip2CompressionInputStream.read(BZip2Codec.java:502)
[info] at com.databricks.spark.xml.XmlRecordReader.readUntilEndElement(XmlInputFormat.scala:194)
[info] at com.databricks.spark.xml.XmlRecordReader.next(XmlInputFormat.scala:143)
[info] at com.databricks.spark.xml.XmlRecordReader.nextKeyValue(XmlInputFormat.scala:128)

**Comment by HyukjinKwon** [comment] 2016-11-23 00:39
Thank you for reporting this. I will try to reproduce this soon.

**Comment by frascuchon** [comment] 2017-01-13 17:27
Using one core works well . I think is related with [https://issues.apache.org/jira/browse/HADOOP-10614](url)

**Comment by srowen** [comment] 2018-12-21 18:19
Looks like this is indeed a Hadoop issue, that should be fixed from 2.5 onwards.
https://issues.apache.org/jira/browse/SPARK-1861

**Closed by srowen** 2018-12-21 18:19 UTC
