### ISSUE TITLE
Unable to run the example

### ISSUE THREAD

**Issue by Rocknpools** [databricks/spark-xml#16] opened 2015-12-05 10:31 UTC
I've imported spark-xml_2.11-0.1.2.jar generated by sbt inside my library in intellij 15

but when i try to run this class:

``` Java
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.sql.SQLContext;
import org.apache.spark.sql.DataFrame;

public class Main {
    public static void main(String[] args) throws Exception {
        // Create a Java Spark Context.
        SparkConf conf = new SparkConf().setMaster("local").setAppName("xmlParser");
        JavaSparkContext sc = new JavaSparkContext(conf);



        SQLContext sqlContext = new SQLContext(sc);
        DataFrame df = sqlContext.read()
                .format("org.apache.spark.sql.xml")
                .option("rootTag", "book")
                .load("/Users/Paolo/Developer/Java/ProgettoAnalisiDati-ArticleMiner/src/main/java/spark/jobs/books.xml");

         df.select("author", "id").collect();
    }
}
```

i get this error:

> Exception in thread "main" java.lang.ClassNotFoundException: Failed to load class for data source: org.apache.spark.sql.xml.
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:67)
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:87)
>     at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
>     at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
>     at spark.jobs.Main.main(Main.java:21)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.xml.DefaultSource
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:60)
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4$$anonfun$apply$1.apply(ResolvedDataSource.scala:60)
>     at scala.util.Try$.apply(Try.scala:161)
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:60)
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$$anonfun$4.apply(ResolvedDataSource.scala:60)
>     at scala.util.Try.orElse(Try.scala:82)
>     at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:60)
>     ... 9 more

what i'm doing wrong?

**Comment by HyukjinKwon** [comment] 2015-12-07 00:48
This jar has been not uploaded properly to Maven central yet ( and also not properly tested for importing). 

As you might notice, this has moved from my private repository to Databricks only couple of weeks ago and this is the reason why a release for this has not been published. (the package name is even not yet updated to `com.databricks.*` and license stuff).

To cut it short, I recommend you use this a bit later. However, if you would like to use this right now urgently, you might need to manually build this for now (as described [here](https://github.com/databricks/spark-xml#building-from-source)), while I am testing and correcting this library to work this properly.

If this is a problem from a jar manually built, I will reproduce and test this case!

**Comment by HyukjinKwon** [comment] 2015-12-07 03:44
Just to make the command above clear, I changed the package name from `org.apache.*` to `com.databricks.*` but did not change the document yet.

If you made it successfully importing, then try to use `com.databricks.xml` instead of `org.apache.spark.sql.xml`.

I will update the document as soon as possible.

**Comment by HyukjinKwon** [comment] 2015-12-07 06:18
I just updated the `README.md`.

**Comment by Rocknpools** [comment] 2015-12-07 09:17
I had already imported it through the manually builded jar. I have tried to use "com.databricks.xml" instead of "org.apache.spark.sql.xml" but unfortunately i got this error:

>
12/07 08:32:42 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NoSuchMethodError: scala.runtime.BooleanRef.zero()Lscala/runtime/BooleanRef;
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.checkObjectType(DomXmlParser.scala)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.inferDataType(DomXmlParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.com$databricks$spark$xml$parsers$dom$DomXmlPartialSchemaParser$$inferField(DomXmlPartialSchemaParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:121)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:119)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.foreach(DomXmlParser.scala:37)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.inferObject(DomXmlPartialSchemaParser.scala:119)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:62)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:50)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15/12/07 08:32:42 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.NoSuchMethodError: scala.runtime.BooleanRef.zero()Lscala/runtime/BooleanRef;
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.checkObjectType(DomXmlParser.scala)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.inferDataType(DomXmlParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.com$databricks$spark$xml$parsers$dom$DomXmlPartialSchemaParser$$inferField(DomXmlPartialSchemaParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:121)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:119)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.foreach(DomXmlParser.scala:37)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.inferObject(DomXmlPartialSchemaParser.scala:119)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:62)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:50)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
15/12/07 08:32:42 INFO SparkContext: Invoking stop() from shutdown hook
15/12/07 08:32:42 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.NoSuchMethodError: scala.runtime.BooleanRef.zero()Lscala/runtime/BooleanRef;
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.checkObjectType(DomXmlParser.scala)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.inferDataType(DomXmlParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.com$databricks$spark$xml$parsers$dom$DomXmlPartialSchemaParser$$inferField(DomXmlPartialSchemaParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:121)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:119)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.foreach(DomXmlParser.scala:37)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.inferObject(DomXmlPartialSchemaParser.scala:119)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:62)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:50)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

And this:

>
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.NoSuchMethodError: scala.runtime.BooleanRef.zero()Lscala/runtime/BooleanRef;
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.checkObjectType(DomXmlParser.scala)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.inferDataType(DomXmlParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.com$databricks$spark$xml$parsers$dom$DomXmlPartialSchemaParser$$inferField(DomXmlPartialSchemaParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:121)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:119)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.foreach(DomXmlParser.scala:37)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.inferObject(DomXmlPartialSchemaParser.scala:119)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:62)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:50)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1496)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1458)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1447)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:567)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1824)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1007)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:989)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1.apply(RDD.scala:1118)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.treeAggregate(RDD.scala:1095)
	at com.databricks.spark.xml.util.InferSchema$.apply(InferSchema.scala:56)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:52)
	at com.databricks.spark.xml.XmlRelation$$anonfun$1.apply(XmlRelation.scala:52)
	at scala.Option.getOrElse(Option.scala:120)
	at com.databricks.spark.xml.XmlRelation.<init>(XmlRelation.scala:51)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:94)
	at com.databricks.spark.xml.DefaultSource.createRelation(DefaultSource.scala:44)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:125)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:114)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:104)
	at spark.jobs.Main.main(Main.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NoSuchMethodError: scala.runtime.BooleanRef.zero()Lscala/runtime/BooleanRef;
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.checkObjectType(DomXmlParser.scala)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.inferDataType(DomXmlParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.com$databricks$spark$xml$parsers$dom$DomXmlPartialSchemaParser$$inferField(DomXmlPartialSchemaParser.scala:74)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:121)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$inferObject$1.apply(DomXmlPartialSchemaParser.scala:119)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at com.databricks.spark.xml.parsers.dom.DomXmlParser.foreach(DomXmlParser.scala:37)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$.inferObject(DomXmlPartialSchemaParser.scala:119)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:62)
	at com.databricks.spark.xml.parsers.dom.DomXmlPartialSchemaParser$$anonfun$apply$2$$anonfun$apply$3.apply(DomXmlPartialSchemaParser.scala:50)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1103)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1104)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by HyukjinKwon** [comment] 2015-12-07 09:22
Ops. Sorry, that should be `com.databricks.spark.xml` as seen in `README.md`.

**Comment by HyukjinKwon** [comment] 2015-12-07 09:26
Hm.. I will try to reproduce this.

**Comment by HyukjinKwon** [comment] 2015-12-07 09:55
```java
String booksFile = "src/test/resources/books.xml";
DataFrame df = sqlContext.read()
    .format("com.databricks.spark.xml")
    .option("rootTag", "book")
    .load(booksFile);
df.select("author", "id").collect();
```

Hm.. I ran this code and looks fine.I suspect the version compatibility.

Would you give me your settings of sbt and Spark version?

**Comment by Rocknpools** [comment] 2015-12-07 10:15
This is the Maven dependency for spark:
```xml
       <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.10</artifactId>
            <version>1.5.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.10</artifactId>
            <version>1.5.2</version>
        </dependency>
```

sbt is the same downloaded from the included shell script

**Comment by Rocknpools** [comment] 2015-12-10 14:51
when i try to import com.databricks.spark module i get this error
![screenshot](https://cloud.githubusercontent.com/assets/7481060/11718264/5a5d989c-9f55-11e5-96fe-920e0d4261bc.png)

seems that this package does not exist but as you can see it is correct imported inside intellij external libraries

**Comment by HyukjinKwon** [comment] 2015-12-11 01:08
Hm.. Would you try to use this a bit later? I will try to publish a release (and upload to maven central) as soon as I can, including this test.

**Comment by dougneedham** [comment] 2015-12-14 16:12
Should this work from a notebook within databricks after adding the package via spark-packages through the databricks UI? 

val df = sqlContext.read
    .format("org.apache.spark.sql.xml")
    .option("rootTag", "book") // This should be always given.
    .load("/mnt/XML/books.xml")

The response I get when looking through the logs is: Found class org.apache.hadoop.mapreduce.TaskAttemptContext, but interface was expected

**Comment by HyukjinKwon** [comment] 2015-12-14 23:08
@dougneedham Would you try with `com.databricks.*` as said in `README.md` with this version?

Actually, It sounds like you tried that with the one in my personal repository (since only that is uploaded as Spark package). For the package, it does not work with lower hadoop version (namely 1.x), which would be corrected with this PR https://github.com/databricks/spark-xml/pull/14.

**Comment by HyukjinKwon** [comment] 2015-12-14 23:20
FYI, any release is not published yet for this repo so you might need to build manually.
I will try to publish a release as soon as possible, maybe right after the PRs for now are closed.

**Comment by HyukjinKwon** [comment] 2015-12-21 05:45
@Rocknpools
Would you like to try set the dependency as below?
```
        <dependency>
            <groupId>com.databricks</groupId>
            <artifactId>spark-xml_2.10</artifactId>
            <version>0.2.0</version>
        </dependency>
```
I just uploaded this and tested. Should be okay.

**Comment by HyukjinKwon** [comment] 2015-12-21 05:46
@dougneedham 
Would you like to try this one please if it is not too late :)?
```bash
$SPARK_HOME/bin/spark-shell --packages com.databricks:spark-xml_2.11:0.2.0
```

**Comment by HyukjinKwon** [comment] 2016-09-09 10:38
Let me please mark this as a question just in order to manage the issues. Please let me know if this still happens.

**Comment by HyukjinKwon** [comment] 2016-12-27 09:46
I am closing this for now. Please reopen or request opening this if anyone meets this issue.

**Closed by HyukjinKwon** 2016-12-27 09:46 UTC
Labels: question

**Comment by praveenchaudhary0602** [comment] 2017-08-08 05:49
XmlReader cannot be resolved to a type , getting this compilation error while trying to set up the code in scala IDE .

**Comment by praveenchaudhary0602** [comment] 2017-08-08 05:49
XmlOptions cannot be resolved
