### ISSUE TITLE
Adds an option to disable schema inference

### ISSUE THREAD

**Issue by skm235** [databricks/spark-xml#223] opened 2016-12-27 08:19 UTC
I have the below sample xml.

<?xml version="1.0" encoding="UTF-8"?>
<root>
   <object1>
      <object_out1>
         <fields>
            <field>
               <innerfield>
                  <innerfield_code>ABC</innerfield_code>
                  <seat>054D</seat>
               </innerfield>
            </field>
         </fields>
      </object_out1>
   </object1>
   <object2>
      <object_out2>
         <fields>
            <field>
               <innerfield>
                  <innerfield_code>DEF</innerfield_code>
                  <seat>0545</seat>
               </innerfield>
            </field>
         </fields>
      </object_out2>
   </object2>
</root>

scala> val df=sqlContext.read.format("com.databricks.spark.xml").option("rowTag","root").load("/user/sample_schema_xml_github.txt")
df: org.apache.spark.sql.DataFrame = [object1: struct<object_out1:struct<fields:struct<field:struct<innerfield:struct<innerfield_code:string,seat:double>>>>>, object2: struct<object_out2:struct<fields:struct<field:struct<innerfield:struct<innerfield_code:string,seat:bigint>>>>>]

scala> df.printSchema()
root
 |-- object1: struct (nullable = true)
 |    |-- object_out1: struct (nullable = true)
 |    |    |-- fields: struct (nullable = true)
 |    |    |    |-- field: struct (nullable = true)
 |    |    |    |    |-- innerfield: struct (nullable = true)
 |    |    |    |    |    |-- innerfield_code: string (nullable = true)
 |    |    |    |    |    |**-- seat: double (nullable = true)**
 |-- object2: struct (nullable = true)
 |    |-- object_out2: struct (nullable = true)
 |    |    |-- fields: struct (nullable = true)
 |    |    |    |-- field: struct (nullable = true)
 |    |    |    |    |-- innerfield: struct (nullable = true)
 |    |    |    |    |    |-- innerfield_code: string (nullable = true)
 |    |    |    |    |    |**-- seat: long (nullable = true)**

Its converting 054D to 54.0 and 0545 to 545.0. is there any way we can keep everything as STRING or we can disable the schema inference ? Actual XML is a very complex xml with nested attributes. Its not easy to prepare custom schema.

Thanks for your help.

**Comment by skm235** [comment] 2016-12-27 08:48
<?xml version="1.0" encoding="UTF-8"?>
<root>
   <object1>
      <object_out1>
         <fields>
            <field>
               <innerfield>
                  <innerfield_code>ABC</innerfield_code>
                  <seat>054D</seat>
               </innerfield>
            </field>
         </fields>
      </object_out1>
   </object1>
   <object2>
      <object_out2>
         <fields>
            <field>
               <innerfield>
                  <innerfield_code>DEF</innerfield_code>
                  <seat>0545</seat>
               </innerfield>
            </field>
         </fields>
      </object_out2>
   </object2>
</root>

**Comment by HyukjinKwon** [comment] 2016-12-27 09:30
I see. Would you be possible to work around as something like as below?

```scala
def toStringSchema(schema: StructType): StructType = {
  def asStringField(f: StructField): StructField = f.dataType match {
    case _: AtomicType => StructField(f.name, StringType, f.nullable)
    case at: ArrayType =>
      // In XML, ArrayType will always have StructType as their elements.
      StructField(f.name, ArrayType(toStringSchema(at.elementType.asInstanceOf[StructType])), f.nullable)
    case st: StructType => StructField(f.name, StructType(st.map(asStringField)), f.nullable)
  }

  StructType(schema.map(asStringField))
}


val stringSchema = toStringSchema(spark.read.format("xml").load("your-path").schema)
spark.read.format("xml").schema(stringSchema).load("your-path").show()
```

or maybe..

```scala
implicit class StringStructType(schema: StructType) {
  def asStringSchema: StructType = StructType(schema.map(asStringField(_)))

  private def asStringField(f: StructField): StructField = f.dataType match {
    case _: AtomicType => StructField(f.name, StringType, f.nullable)
    case at: ArrayType =>
      // In XML, ArrayType will always have StructType as their elements.
      StructField(f.name, ArrayType(at.elementType.asInstanceOf[StructType].asStringSchema), f.nullable)
    case st: StructType => StructField(f.name, StructType(st.map(asStringField(_))), f.nullable)
  }
}

val stringSchema = spark.read.format("xml").load("your-path").schema.asStringSchema
spark.read.format("xml").schema(stringSchema).load("your-path").show()
```

**Comment by HyukjinKwon** [comment] 2016-12-27 09:31
This introduces unused schema inference. Maybe, we need an option to disable it. Let me tag this as an enhancement. Would you mind if I ask to change the title to something like "Adds an option to disable schema inference" if you are fine with this title?

**Comment by HyukjinKwon** [comment] 2016-12-27 10:01
Ah, actually, this turns to a duplicate of https://github.com/databricks/spark-xml/issues/205 I think.

**Comment by skm235** [comment] 2016-12-27 10:20
Thanks for your help. wow. The workaround really worked. Please go ahead and rename it like "Adds an option to disable schema inference".

**Comment by skm235** [comment] 2016-12-27 11:40
can i store the generated schema in a file and use it like .avsc for avro  to parse the xml document ?

**Closed** 2018-12-20 19:44 UTC
Labels: enhancement
