### ISSUE TITLE
Issue with using com.databricks:spark-xml_2.11:0.6.0  for loading xmls

### ISSUE THREAD

**Issue by madhusudhan-tmnas** [databricks/spark-xml#405] opened 2019-08-30 12:54 UTC
Using the new version of databricks api (com.databricks:spark-xml_2.11:0.6.0 )  fetching null values, when XML's are loaded into dataframe.
Initially we had a issue with using com.databricks:spark-xml_2.10:0.4.0 i,e trimming the leading zeros for an attribute in the xml after loading into the XML.  After using the new version (2.11:0.6.0)  the issue got resolved and data is populating the prefix zeroes but we are facing issue with using new API.  using old API i,e com.databricks:spark-xml_2.10:0.4.0 we could able to populate data .

We are facing the problem only while loading the bulk XML's in to dataframe. We dont have issue while loading single XML into Dataframe.

Summaray:

---> com.databricks:spark-xml_2.10:0.4.0  has trimming leading zero issue, could not make infer schema false

--->  com.databricks:spark-xml_2.11:0.6.0  trimming leading zero issue resolved but values are polulating as null

Please Find below code for better understand.

########spark with databricks com.databricks:spark-xml_2.11:0.6.0########
##############################################################
scala> val dataload=spark.read.format("com.databricks.spark.xml").option("rowTag", "root").load("/datalake/xxxx/spirepl/policy_repo/xml_load/aqs/*")

scala> dataload.selectExpr("Policy.TransactionInfo.PolicyId").where("messageid='XXXXX-XXXX-XXXXX-XXXXX-XXXXXXXX'").show(false)
+--------+
|PolicyId|
+--------+
|null    |
+--------+

scala> d.selectExpr("Policy.PolicyNumber").where("messageid='XXXXX-XXXX-XXXXX-XXXXX-XXXXXXXX'").show(false)
+------------+
|PolicyNumber|
+------------+
|null        |
+------------+

########spark with databricks com.databricks:spark-xml_2.10:0.4.0#####################
###################################################################

  
Using spark-xml_2.10:0.4.0 version, we could able to populate the actual value from data frame

scala> val dataload=spark.read.format("com.databricks.spark.xml").option("rowTag", "root").load("/datalake/xxxxx/spirepl/policy_repo/xml_load/aqs/*")

scala> dataload.selectExpr("Policy.TransactionInfo.PolicyId").wherewhere("messageid='XXXXX-XXXX-XXXXX-XXXXX-XXXXXXXX'").show(false)
+--------------------+
|PolicyId            |
+--------------------+
|[XXXXXX, YYYYYY]|
+--------------------+

scala> d.selectExpr("Policy.PolicyNumber").where("messageid='XXXXX-XXXX-XXXXX-XXXXX-XXXXXXXX'").show(false)
+------------+
|PolicyNumber|
+------------+
|XXXXXYYYYYY|
+------------+

**Comment by srowen** [comment] 2019-08-30 13:19
I think we'd have to see some of the XML to say more. What leading zero are you talking about?
What happens if you specify the schema manually (or, what is the type of PolicyNumber?)

**Comment by auserlogin** [comment] 2019-08-30 14:44
The leading zero problem was fixed by the new feature you added, "inferSchema".  The problem is the new version is no longer allowing a bulk load of XMLs which wasn't a problem with version 2.10:0.4.0

**Comment by srowen** [comment] 2019-08-30 15:21
As I say, we'd have to see some input to understand whether the output is correct.

**Closed** 2019-09-11 13:27 UTC
